language: java
dist: xenial
sudo: false
install: true

addons:
  sonarcloud:
    organization: "clecoq75-github"

script:
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
