language: java
dist: xenial
sudo: false
install: true

addons:
  sonarcloud:
    organization: "clecoq75-github"

script:
  - mvn clean install -B
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=cle.mail:mail-utils

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
